### ISSUE TITLE
Demo repeats first animation

### ISSUE THREAD

**Issue by rapito** [sachinchoolur/angular-flash#10]
On the [demo](http://sachinchoolur.github.io/angular-flash/) page, when you click on one of the buttons for the first time, the animation gets repeated after the alert finishes it's first transition.

**Comment by RoopeHakulinen** [comment]
Hey @rapito,

thank you for your feedback. I didn't find that happening anymore on version 2. Could you please let me know if you still see this happening. Closing for now.

**Comment by rapito** [comment]
@RoopeHakulinen Its not happening anymore, thanks!
