### ISSUE TITLE
Not possible use flash message by id

### ISSUE THREAD

**Issue by rfanjul** [sachinchoolur/angular-flash#11]
If there are a few Flash messages in the same page, all of them would be throw when we expect only one of them. Throw message by message id should be possible.

**Comment by mwgi2005** [comment]
Yeah I've got the same question, is there anyway we can trigger any specific one ?

**Comment by rbrink1995** [comment]
I just used the ng-show/hide attribute to mask the alerts that I don't want shown, but I agree this would be nice to have baked into the directive

**Comment by RoopeHakulinen** [comment]
I suppose this problem doesn't exist anymore on version 2, right?

**Comment by RoopeHakulinen** [comment]
If I understand you correctly, this is already possible now as `Flash.create` method returns id that can be used to call Flash.`dismiss(id)`. Please feel to reopen if I missed something.

**Comment by Nytrox** [comment]
If I have 2 flash-messages in the HTML file (I want a different flash message to show in different places), they still show up in both places.

**Comment by RoopeHakulinen** [comment]
Oh right, you mean that it should be possible to have multiple `flash-message` directives on single page with different messages. I'll have a look at that when I find time to do so. Meanwhile, PRs are welcomed.

**Comment by arithmetric** [comment]
It looks like an approach is started in this fork: https://github.com/johnsardine/angular-flash/commit/fca1026a548be2efd066bc831cec89818e44498a

**Comment by RoopeHakulinen** [comment]
I'd be happy to see a PR for this when done :)

**Comment by RoopeHakulinen** [comment]
I'd be happy to see a PR for this when done :)

**Comment by holtalanm** [comment]
completely did not read this issue all the way through when I submitted #32.

Looks like this is exactly the issue I was having.  Got it working, and submitted a pull request for it.  #33

**Comment by RoopeHakulinen** [comment]
Should be possible with 2.4.0 as far as I can see.
