### ISSUE TITLE
Flash Message optional timeout is not working

### ISSUE THREAD

**Issue by pratik60** [sachinchoolur/angular-flash#15]
```<div flash-message="10000" ></div>```

If we do this, the value that is picked up by the plugin is the default one of 5000. Reason being is the order of execution

This happens first
timeOut = $timeout(function() {
                    $this.dismiss();
                }, $rootScope.flash.timeout);

This happens second
$rootScope.flash.timeout = parseInt(attrs.flashMessage, 10);

**Comment by sarthak-saxena** [comment]
it seems to work fine in mac OSX but for windows the timer is not working.

we have to manually feed in the timer value.

(function() {
  'use strict';
  var app = angular.module('flash', []);

  app.run(['$rootScope', function($rootScope) {
    // initialize variables
    $rootScope.flash = {};
    $rootScope.flash.text = '';
    $rootScope.flash.type = '';
    $rootScope.flash.timeout = TIMERVALUE;
    $rootScope.hasFlash = false;
  }]);

**Comment by RoopeHakulinen** [comment]
Hey, I wasn't able to reproduce this bug anymore in version 2. Could you guys confirm that it doesn't exist anymore?
