### ISSUE TITLE
How does duration work?

### ISSUE THREAD

**Issue by 21stcn** [sachinchoolur/angular-flash#20]
Maybe I'm missing something but can't seem to get duration to work.

Please check [updated fiddle](http://jsfiddle.net/Latav3y1/)

**Comment by RoopeHakulinen** [comment]
Thank you for reporting this. It is a bug. I'll push a fix for it soon.

**Comment by RoopeHakulinen** [comment]
Fixed and released version 2.2.1. Please let me know if there's any other problems!

**Comment by 21stcn** [comment]
Thanks very much for fixing it and sharing your work.
