### ISSUE TITLE
Fade out animation impossible as ng-hide is applied directly after closing

### ISSUE THREAD

**Issue by troxler** [sachinchoolur/angular-flash#21]
I'm trying to animate the fade out of the messages (fade in works good so far). However, there seems to be a slight glitch in the code that hides the messages instantly after pressing the close button (or after waiting for the timeout) by applying `class="ng-hide"` to the message container. This hides the message instantly which makes an animation impossible.

Angular defines the corresponding CSS as follows:

    .ng-hide:not(.ng-hide-animate) {
        display: none !important;
    }

So I guess all it takes to solve this is to apply `class="ng-hide ng-hide-animate"`, wait for the animation to end and then remove `ng-hide-animate`.

**Comment by RoopeHakulinen** [comment]
Thank you so much for valuable feedback and sorry for a long delay on my response. It seems there is unnecessary `ng-hide` as you mentioned. I'll remove it tomorrow, update the JSFiddle and CodePen to reflect it and publish better documentation on this subject.

**Comment by RoopeHakulinen** [comment]
Sorry it took a little longer than I promised. Hope it works now as you wish it to work and please let me know if you have any further problems with the library.

**Comment by troxler** [comment]
@RoopeHakulinen Thank you very much for the quick resolution. One remark though, there is now a version mismatch between bower.json and package.json. And in dist/angular-flash.js, there is an even older version mentioned.

Could you please also tag the version appropriately? Thank you.

**Comment by RoopeHakulinen** [comment]
I'll fix that version number next time on _angular-flash.js_ and in _bower.json_. At least the Bower and NPM show the same version now for same (newest) code. Thank you for letting me know, though as I had forgotten to do the version release for Bower.
