### ISSUE TITLE
Flash dismiss not close the message

### ISSUE THREAD

**Issue by lauort** [sachinchoolur/angular-flash#23]
Hi,

I have a form that show a message if the login fails, but the message are showing one under other, I tried to put the Flash.dismiss but the flash message is not closed when you click on the login button.

Regards.

**Comment by RoopeHakulinen** [comment]
Hey, thank you for reporting this. This is now fixed in version 2.2.5 after issue #24.

**Comment by lauort** [comment]
@RoopeHakulinen No problem :)
