### ISSUE TITLE
explorer issue

### ISSUE THREAD

**Issue by odedkeren1** [sachinchoolur/angular-flash#24]
angular-flash doesnt work on IE
try your self even, go to http://sachinchoolur.github.io/angular-flash/
and try to click on the X button to close the flash object.
the problem is in line 134 at angular-flash.js
function findIndexById(id) {
            return $rootScope.flashes.findIndex((flash) => {
                return flash.id === id;
            });
object doesn't support method findIndex

**Comment by RoopeHakulinen** [comment]
Thank you so much for reporting this. It seems that the _findIndex_ isn't transpiled by Babel for some reason. I'll push a patch for this ASAP and release 2.2.5.
