### ISSUE TITLE
Error when angular-flash is configured with ui-router

### ISSUE THREAD

**Issue by game013** [sachinchoolur/angular-flash#25]
Hello.

I'm using angular-flash to show messages and when I tried to clear all messages when state is changed successfully, I get this error:

> angular.js:13424 Error: [$rootScope:inprog] $apply already in progress
> http://errors.angularjs.org/1.5.3/$rootScope/inprog?p0=%24apply
>     at angular.js:68
>     at beginPhase (angular.js:17383)
>     at Scope.$digest (angular.js:16821)
>     at Object.dataFactory.dismiss (angular-flash.js:113)
>     at Object.dataFactory.clear (angular-flash.js:129)
>     at message.service.js:42
>     ....

In order to clarify the issue, here is the code in _message.service.js_ line 42:

`$rootScope.$on('$stateChangeSuccess', function() {
     Flash.clear();
  });`

I hope you can help me, thanks in advance.

**Comment by RoopeHakulinen** [comment]
Hey, thank you for reporting. Could you please verify that release 2.2.6 fixes the issue?
