### ISSUE TITLE
Creating flash messages over multiple screens

### ISSUE THREAD

**Issue by maa42** [sachinchoolur/angular-flash#26]
I have multiple Flash messages setup across different screens :
Ex.              var message  ="User Successfully Logged Out";
                    Flash.create('success', message,0);

Any message that is not dismissed by clicking on the close button or using Flash.dismiss() queues up and pops up whenever I just want to see the one created for the page I'm looking at.   I tried to add a Flash dismiss() prior to every create but I get a digest already in progress error every so often.

**Comment by RoopeHakulinen** [comment]
Hey @maa42 and thank you for reporting this. Could you please check which version of _angular-flash_ are you using? If it isn't the newest version released last week, would it be possible for you to try with that? 

There is also a method called _clear_ (usage: `Flash.clear();`) which should clear all flashes.

**Comment by RoopeHakulinen** [comment]
Actually this wasn't fixed by 2.2.6 because of my mistake. There is now version 2.2.7 available that fixes this. Please reopen if you still encounter any problems related.
