### ISSUE TITLE
Unknown provider when using minified version

### ISSUE THREAD

**Issue by ahmed-hachena** [sachinchoolur/angular-flash#3]
When I use the minified version I get a Unpr error. The **run** function is missing the **"$rootScope"** annotaion  in the dist files.

**Comment by sachinchoolur** [comment]
Hi,
It works fine form me. I have updated demo website with minified version..
Please download latest files and check.

**Comment by ahmed-hachena** [comment]
Hi,
It seems that the problem comes from Bower, when I install the module with it the minified version doesn’t work and I get the previous error.
I don't have any idea how Bower works, you may want to check it because the dist files works perfectly when I clone it directly from Github.
thanks

**Comment by sachinchoolur** [comment]
Hi,
There was an issue with minified version of angular-falsh. I had fixed it but forgot to update bower and npm.. 
Thanks for pointing this out I have fixed this. Please check..

**Comment by ahmed-hachena** [comment]
Hi,
It works perfectly now, good job.
