### ISSUE TITLE
Flash Showing Multiple Messages

### ISSUE THREAD

**Issue by agam16** [sachinchoolur/angular-flash#30]
I am using the flash message on login screen, and when user click login multiple times with invalid creds, it forces the login to go down and down by showing multiple error messages. Is there a way so that the flash message updates or overwrite the previous message

**Comment by RoopeHakulinen** [comment]
Thank you for your feedback. There isn't currently an option to achieve this straightaway but you can easily achieve this by calling `Flash.clear();` before `Flash.create` to clear all current flashes. I might add this as a feature at some point if I find the time though.

**Comment by agam16** [comment]
Thanks for reply . I tried the clear method before create method. Now once it works fine, But when i click login again before it disappears, It throws a error. 
"Error: [$rootScope:inprog] $digest already in progress"

**Comment by RoopeHakulinen** [comment]
Just to confirm that you are using the latest version 2.2.7? There have been problems with the digest in the earlier versions but none reported anymore.

**Comment by zgordon01** [comment]
I have completed a fix for this on my local machine. What is the process for contributing to this repo?

**Comment by zgordon01** [comment]
The fix involves a new FlashProvider.setAutoDismiss(boolean) that essentially only allows one flash message at a time

**Comment by zgordon01** [comment]
I have made a pull request adding the mentioned feature. https://github.com/sachinchoolur/angular-flash/pull/51

**Comment by scaryguy** [comment]
+1. I think it'd be great as a feature.

**Comment by RoopeHakulinen** [comment]
Sorry for taking so long to react. 

If you are interested in taking this project in maintenance, please let me know since I haven't done AngularJS basically in 1,5 years now as Angular 2+ has been around.

I'll try to publish in the npm in a minute as I get everything set up again.

**Comment by RoopeHakulinen** [comment]
As the changes of PR were introduced into the distributable code instead of sources, I needed to manually copy those and also fix the tests to pass again. Hope it went appropriately and the feature is now as you wished.

Anyways, version 2.5.0 is now released on npm and Bower. Please verify it works as you wish @zgordon01  and let me know here so the issue can be re-opened if not :) 

Thank you for your contribution.

**Comment by zgordon01** [comment]
My bad I guess I added my changes into the wrong spot. It looks good to me!

I see my mistake now. Won't make it again! Thank you for formatting my contribution and deploying it
