### ISSUE TITLE
New contributor, various proposals

### ISSUE THREAD

**Issue by ncoden** [sachinchoolur/angular-flash#34]
Hi.

I just point out here that I begin to use this package (for [CaliOpen](https://github.com/CaliOpen/caliopen.web-client-ng)), and I am very demanding and picky on my Js/CSS. So I will start to contribute to this package, with four goals:
- Allow to use its own flash template with custom datas
- Improve the way to configure the plugin
- Improve the package code readability (and clean the CSS, give it a namespace !)
- Maybe, make all the Bootstrap stuff independent (because some people don't use Bootstrap, or don't want to load useless Js)

I hope these contributions will be appreciated :)
Please give me a feedback about it before I start making PRs.

Nicolas

**Comment by RoopeHakulinen** [comment]
Hey,

nice to hear you are interested. It would be greatly appreciated if you did all the things you mentioned. I'll comment them shortly point by point:

- It wouldn't certainly hurt to be able to pass your own template for flash so :+1: 
- Did you have some pre-thought ideas on improving the configuring? Hard to comment too much with this info.
- CSS has been like it's been from the beginning, and as you said it would be nice to namespace it. Also there's been some improvements on code readability, but a bigger rewrite wouldn't be bad thing.
- The Bootstrap has always been an essential part of this module they way I see it. When I first found this module, it was just the Bootstrap-compatibility that was the trigger for me to use it over the various other alternatives already available. It would certainly be nice to have it work with and without Bootstrap but with the precondition that using Bootstrap alerts would work seamlessly. This is something that I see quite important. 

In general I just hope that the future improvements would keep it as simple to use as nowadays by providing good defaults in case you skip configuration. For example the default template should be used if non is provided and so on. You get the point.

So to conclude, please feel free to start making those PRs, I'll promise to check those ASAP.
