### ISSUE TITLE
sourceMappingUrl in not minified file breaks Rails 4

### ISSUE THREAD

**Issue by morynicz** [sachinchoolur/angular-flash#35]
On the bottom of _dist/angular-flash.js_ there is a
131 //# sourceMappingURL=angular-flash.js.map
sitting, which blows up my Rails app :)

This should probably go to _dist/angular-flash.min.js_ so the mapping can be found when You are using the minimified version.

**Comment by RoopeHakulinen** [comment]
Thank you for letting me know. I will take a look as soon as possible.

**Comment by RoopeHakulinen** [comment]
It is actually there on purpose as the original file is ES6 and it maps to that. It is also a JavaScript comment so it shouldn't break too much. Could you explain a little how it blows up your Rails app? Is it the asset precompilation and if so what is the error?

There should also be map for the .min.js so I added one there now.

**Comment by morynicz** [comment]
I get:
ERROR ActionController::RoutingError: No route matches [GET]
"/assets/angular-flash.js.map"

This does look like something that can be resolved on my side but that's
the first time I see a library behave like that. Other libraries I have do
not include the map file for not minified version of js, so I assumed
something might be wrong on library's side.

Pozdrawiam,
Michał Orynicz

2016-04-24 10:09 GMT+02:00 Roope Hakulinen <notifications@github.com>:

**Comment by morynicz** [comment]
Ok, It seems that problem lies in rails sprockets: https://github.com/rails/sprockets/issues/284 , https://github.com/rails/sprockets/issues/157
So not much to do on angular-flash side.

**Comment by RoopeHakulinen** [comment]
Thank you for getting back on this. I'll close the ticket for now. Please let me know if there is something that I can help you with still.
