### ISSUE TITLE
Use the same name across api, repo and package managers

### ISSUE THREAD

**Issue by ncoden** [sachinchoolur/angular-flash#37]
I think we should use only one name across the API, this repo and the package managers (npm...).

For the moment, we have:
- `angular-flash` for github repo and filenames
- `angular-flash-alert` for npm, bower
- `ngFlash` for the angular module
- `flashMessage` for the main directive
- `Flash` for the service
- `dataFactory` (wtf?) inside the service

**Comment by RoopeHakulinen** [comment]
Those are pretty much the names that have existed there from the beginning. 

I assume the plan of Sachin was originally to name it _angular-flash_ but then it was already taken on NPM and Bower and thus the _angular-flash-alert_. Maybe the repo could be renamed if Bower and NPM survive from it. 

_ngFlash_ was originally only flash, and I renamed it to match the naming convention of Angular modules. 

_flashMessage_ is from the time there was limit of only one flash shown simultaneously. Maybe it could be renamed at some point to at least be plural.

The problem with changing most of these is that they are breaking changes which force the module users to make unnecessary changes on their code without getting any actual benefit from it.

**Comment by ncoden** [comment]
The problem with changing most of these is that they are breaking changes which force the module users to make unnecessary changes on their code without getting any actual benefit from it.

Yes. These renaming ideas are for a future v3 :)
