### ISSUE TITLE
Animation not working because of markup/css issue

### ISSUE THREAD

**Issue by henk23** [sachinchoolur/angular-flash#42]
```
.alert.ng-leave {
  opacity: 1;
  transition: opacity 1.5s ease-out;
}
.alert.ng-leave-active {
  opacity: 0;
}
```

This snippet from the README file cannot work, because the markup looks like this:
```
<div ng-repeat="flash in $root.flashes track by $index" class="[...ng-enter/ng-leave/etc...]">
    <div role="alert" class="alert alert-success alertIn alertOut">[...message...]</div>
</div>
```

So the inner div with the alert class will not get the ngAnimation classes.
Would possibly be good to add an "alert-container" class to the outer div.

**Comment by henk23** [comment]
#43

**Comment by RoopeHakulinen** [comment]
Added the class mentioned in PR with 2.4.0. Thank you so much for your efforts!
