### ISSUE TITLE
is multiple container allowed?

### ISSUE THREAD

**Issue by eduarguzher** [sachinchoolur/angular-flash#48]
I would like to have 2 flash message containers on the same page, is that possible?

I modified the Example code and created them both, using the create function emits to all <flash-message>
How does work the 'name' property and the 'container' setting
` <flash-message name='one' duration="5000"></flash-message>
    <flash-message name='two' duration="5000"></flash-message>`
`    Flash.create('success', message, 0, {container: 'one'});`

http://jsfiddle.net/uxeg4nze/30/

**Comment by matinfo** [comment]
YES, but first use the last version 2.4.0. Here your jsfiddle updated with multi-containers usage example: http://jsfiddle.net/uxeg4nze/32/

**Comment by eduarguzher** [comment]
@matinfo oh right, it was the problem... thanks for reply 
but checking my project, i am using bower which seems to install the 2.3.0 version

bower package is not updated, i hope they update it soon
`Available versions in https://github.com/sachinchoolur/angular-flash.git: 2.3.0, 2.2.7, 2.2.6, 2.2.5, 2.2.4, 2.2.3, 2.2.1, 2.2.0, 2.0.0, 1.1.1, 1.1.0, 1.0.0`

**Comment by RoopeHakulinen** [comment]
@eduarguzher I'm so sorry for the missing Bower release. Good that you brought it to my attention. I just drafted the release and it should be available via Bower soonish.

Thank you also @matinfo for your answer :) 

Have a nice day!
