### ISSUE TITLE
All the flashes defined in HTML will be recreated on any specific flash call.

### ISSUE THREAD

**Issue by Anoop-Goudar** [sachinchoolur/angular-flash#49]
Hi,
I need a flash message FM-A at the top of the page on lets say action A, and I need another flash message FM-B somewhere on the middle of the page. 
I have defined two flash messages with different flash names defined.
If I create FM-B, FM-A is also getting created irrespective of the names defined.

Could you please verify the issue ?

**Comment by sanjeevkpandit** [comment]
I am also getting the same issue.

**Comment by Foris-master** [comment]
Hi, 
you have to use multiple flash containers,
you can send flashes to different containers by naming them and specifying their name in the config you pass to the Flash.create function.
`<flash-message name="flash-fixed"></flash-message>` in your template 
`Flash.create('success', 'Hooray!', 0, {container: 'flash-fixed'});` in your controller

**Comment by RoopeHakulinen** [comment]
@Anoop-Goudar please let me know if you are still experiencing this problem with 2.5.0 and we'll re-open this issue.
