### ISSUE TITLE
Multi-line flash message

### ISSUE THREAD

**Issue by sethanuj** [sachinchoolur/angular-flash#54]
When showing flash messages that span multiple lines, the close button (x) on the right is misaligned. 

I cannot show each error in a different flash message, but need to show it consolidated in a single one. Let me know what CSS fix/hack is required to ensure the close icon is properly aligned. 

Thanks!

**Comment by spjoshis** [comment]
I checked this issue but seems like everything is fine. you can use `<div>` in the message.
