### ISSUE TITLE
Add ability to call some code once the flash message is dismissed

### ISSUE THREAD

**Issue by strelok1** [sachinchoolur/angular-flash#7]
Hi,

It would be good to add an ability to add a callback to be executed when flash message is dismissed (either by timeout or by user). Something like this:

    <div flash-message="5000" flash-message-dismiss="doSomething()"/>

Cheers

PS. If I get a chance I will submit a pull request for this.

**Comment by RoopeHakulinen** [comment]
Hey @strelok1,

thank you for your idea. I'd love to see a PR for that! I'll might do it also myself if I find the time.
