### ISSUE TITLE
Reference to flash elements

### ISSUE THREAD

**Issue by edriang** [sachinchoolur/angular-flash#8]
I really liked this module, but I'd like to see the following feature that is present in this other library:

https://github.com/wmluke/angular-flash

Following that module idea, you can specify some id to the flash-message directive, so then when you call Flash.create service you could set target id too.

ie:

<div flash-message="5000"></div>

<div id="login-flash" flash-message="5000"></div>

Flash.create('success', message, 'custom-class', 'login-flash');

//Or better you could make last parameter as a config object
Flash.create('success', message, {
    class: 'custom-class', 
    target: 'login-flash'
});

**Comment by RoopeHakulinen** [comment]
Hey @edriang,

thank you for your feedback. That would actually be quite neat so I'll have a look at that soon.
