### ISSUE TITLE
Alert fails to hide because of error

### ISSUE THREAD

**Issue by paulstefanday** [sachinchoolur/angular-flash#9]
Whenever the alert tries to hide it fails and gives this error:

TypeError: $this.dismiss is not a function
    at angular-flash.js:75
    at angular.js:16303
    at completeOutstandingRequest (angular.js:4928)
    at angular.js:5316
    at e (raven.min.js:2)

It's something to do with "var $this = this;" not working when called in 
"timeOut = $timeout(function() { $this.dismiss(); }, $rootScope.flash.timeout); "

It works fine when I use the functions code instead of calling "$this.dismiss();". Any idea what could be wrong? 

This is from this part of the code:

 app.factory('Flash', ['$rootScope', '$timeout',
        function($rootScope, $timeout) {

            var dataFactory = {},
                timeOut;

            // Create flash message
            dataFactory.create = function(type, text, addClass) {
                var $this = this;
                $timeout.cancel(timeOut);
                $rootScope.flash.type = type;
                $rootScope.flash.text = text;
                $rootScope.flash.addClass = addClass;
                $timeout(function() {
                    $rootScope.hasFlash = true;
                }, 100);
                timeOut = $timeout(function() {
                    $this.dismiss();
                }, $rootScope.flash.timeout);
            };

            // Cancel flashmessage timeout function
            dataFactory.pause = function() {
                $timeout.cancel(timeOut);
            };

            // Dismiss flash message
            dataFactory.dismiss = function() {
                $timeout.cancel(timeOut);
                $timeout(function() {
                    $rootScope.hasFlash = false;
                });
            };
            return dataFactory;
        }
    ]);

**Comment by RoopeHakulinen** [comment]
Hey @paulstefanday,

thank you for your report. Could you please let me know if this still happens on version 2. I'll have a look if it does. Closing for now.
